### ISSUE TITLE
Design the work-flow, resources for PROJECT-OWNER 

### ISSUE THREAD

**Issue by nivemaham** [RADAR-base/ManagementPortal#10]
Document the work-flow of a project initialization work-flow with a PROJECT-OWNER.

- [x] A project owner will get a username and a link to reset password 
- [x] Once the account is activated he/she can define other Roles for the project he is assigned to. 
- [x] He/she can create other users and assign them to the roles mentioned in 2.
- [x] He/she can design the device catalog of the project ( set of device types and link them to the project)
- [x] He/she can create patients for the project
- [ ] He/she can assign set of devices assigned to his to project to set of patients assigned to his project.
- [x] He/she cannot create new projects
- [x] He/she cannot access/view data from other projects

A PROJECT_OWNER is similar to SYS_ADMIN, but can only handle entities related to his project only.
Only the SYS_ADMIN can have access to all the operations in the portal.

**Comment by fnobilia** [comment]
Let me try to describe the workflow, please correct me if I am wrong.

 **PROJECT OWNER DEFINITION** 
1.  the `SYS_ADMIN` creates a new project `PROJECT_A`
2.  the `SYS_ADMIN` creates a new user `USER_A`
    - required information: username, password and email.
    - the system automatically notifies `USER_A` at the provided email asking for changing password
3.  the `SYS_ADMIN` set `USER_A` as `PROJECT-OWNER` of `PROJECT_A`. Meaning that no other users can be defined as `PROJECT-OWNER` for `PROJECT_A`, and `USER_A` cannot be `PROJECT-OWNER` of any other project
4.  Now `USER_A` for `PROJECT_A`
    * can
        - create new roles (no other can do this thing for `PROJECT_A`)
        - create new users
        - create new subjects (e.g. patient)
        - assign roles to users
        - create new sources  (e.g. device)
        - create new sensors
        - assign sources to users
    * cannot
        - create new projects
        - access other projects

Questions:
1.  How do we initially set email and password for `SYS_ADMIN`?
2.  Is changing password for `USER_A` compulsory? or `USER_A` can start interacting with the system without changing password?
3. Can `USER_A` remove a role from a user within his project?
4. Can `USER_A` remove sources from users (not listed above, sources can be reusable)
5. Is the `subject` a specification of `user`?
6. Let's consider `USER_B` as a new user created by `USER_A` in `PROJECT_A`, can `USER_A` assign roles to `USER_B` to
    - create subjects
    - assign sources to subjects
    - remove sources from subjects
7. Can be `PROJECT-OWNER` removed from `USER_A` and assigned to `USER_B` (see point 5). If yes, who can do that? only `SYS_ADMIN` or `USER_A` too? If no, what happen if `USER_A` leaves the project?
8. Can `USER_A` assign to `USER_B` (see point 5) a role to manage roles? If yes, can `USER_B` remove `PROJECT-OWNER` from  `USER_A` and assign it to himself?
9. Can `PROJECT-OWNER` reset the password of other users?

**Comment by nivemaham** [comment]
Small correction 
**PROJECT OWNER DEFINITION** 
1.  the `SYS_ADMIN` creates a new project `PROJECT_A`
2.  **the `SYS_ADMIN` creates the `PROJECT_ADMIN` role for `PROJECT_A`**
3.  the `SYS_ADMIN` creates a new user `USER_A`
    - required information: username, password and email.
    - the system automatically notifies `USER_A` at the provided email asking for changing password
    - **3.1.  the `SYS_ADMIN` set `USER_A` as `PROJECT-ADMIN` of `PROJECT_A` using role created in 2.**. Meaning that no other users can be defined as `PROJECT-OWNER` for `PROJECT_A`, and `USER_A` cannot be `PROJECT-OWNER` of any other project. **( This should be the ideal case, but not implemented yet. The entity relationship is there)**

4. **`USER_A` resets his password using provided link in the email.**
5.  Now `USER_A` for `PROJECT_A`
    * can
        - create new roles (no other can do this thing for `PROJECT_A`)
        - create new users
        - create new subjects (e.g. patient)
        - assign roles to users
        - create new sources  (e.g. device)
        - create new sensors
        - assign sources to users
    * cannot
        - create new projects
        - access other projects

Questions:
1.  How do we initially set email and password for `SYS_ADMIN`?
**This is the only account that would be provided by the system by default. ( the data is already set in database on initialization of the system). The `SYS_ADMIN` can reset his password before proceeding with other operations.**
2.  Is changing password for `USER_A` compulsory? or `USER_A` can start interacting with the system without changing password?
**Yes. Otherwise the account will remain deactivated and `USER_A` cannot authorize without a known password.**
3. Can `USER_A` remove a role from a user within his project?
**Currently, a role cannot be removed. If we allow this feature a `PROJECT_ADMIN` aka `USER_A` cannot remove this role. Only `SYS_ADMIN` can remove a role, provided that there is no user assigned to corresponding role. ( Need to be implemented. Please visit [issue13](https://github.com/RADAR-CNS/ManagementPortal/issues/13)).**
4. Can `USER_A` remove sources from users (not listed above, sources can be reusable)
**Yes. Should be possible. Not implemented yet.** 
5. Is the `subject` a specification of `user`?
**Yes. Subject extends a subset of User properties. `Subject` has one-to-one relationship between `User`. `Subject` has "subject-specific" (e.g. devices, external id etc) properties and do not have all the properties of a `User` (e.g. email, etc).**
6. Let's consider `USER_B` as a new user created by `USER_A` in `PROJECT_A`, can `USER_A` assign roles to `USER_B` to
    - create subjects **( Depends on which roles are allowed to create subjects)**
    - assign sources to subjects **( Currently, subjects are allocated for a project, not for a user with specific role. So if a user with role X is allowed to do this, USER_B can be assigned role `X` by `USER_A`.** 
    - remove sources from subjects **( Same as the above)**
7. Can be `PROJECT-ADMIN` removed from `USER_A` and assigned to `USER_B` (see point 5). If yes, who can do that? only `SYS_ADMIN` or `USER_A` too? If no, what happen if `USER_A` leaves the project?
**SYS_ADMIN can remove/deactivate `USER_A` and assign `USER_B`. It cannot be done by `USER_A`. ( To be implemented)**
8. Can `USER_A` assign to `USER_B` (see point 5) a role to manage roles? If yes, can `USER_B` remove `PROJECT-OWNER` from  `USER_A` and assign it to himself?
**Currently, only users with `SYS_ADMIN` and `PROJECT_ADMIN` privileges can manage roles and it is expected there is one `PROJECT_ADMIN` per project. Thus, only `SYS_ADMIN` can change the `PROJECT_ADMIN of the project.  This should be discussed in detail.** 
9. Can `PROJECT-OWNER` reset the password of other users? - **Should be investigated.**

**Comment by fnobilia** [comment]
_How do we initially set email and password for SYS_ADMIN?_
**This is the only account that would be provided by the system by default. ( the data is already set in database on initialization of the system). The SYS_ADMIN can reset his password before proceeding with other operations.**

If I have correctly understood, the system has a default `SYS_ADMIN` with for example username `admin` with password `admin`. At the end of the installation, the user has to login as `admin` set his/her email and reset the password. Is this correct?

**Comment by nivemaham** [comment]
Yes. It can be done without directly in the system, without emailing. But can indeed update his/her email.

**Comment by fnobilia** [comment]
From a discussion with @afolarin 

> REDCap allows a user to be `PROJECT-OWNER` of multiple projects.

Having a user as `PROJECT-OWNER` of multiple projects is not so "strange". Think about Phase 1 and Phase 2 of the same project. Each phase can be represented by a project, let's say `P_1` and `P_2`. If `USER_A` is already `PROJECT-OWNER` of `P_1`, then he/she cannot be `PROJECT-OWNER` of `P_2`.

> 3.1. the SYS_ADMIN set USER_A as PROJECT-ADMIN of PROJECT_A using role created in 2.. Meaning that no other users can be defined as PROJECT-OWNER for PROJECT_A, and USER_A cannot be PROJECT-OWNER of any other project. ( This should be the ideal case, but not implemented yet. The entity relationship is there)

What are the differences between `PROJECT-ADMIN` and `PROJECT-OWNER`?

**Comment by nivemaham** [comment]
Currently, We just have PROJECT_ADMIN realized. PROJECT-ADMIN and PROJECT-OWNER are the same in the aforementioned line. Sorry for the confusion. 
From the discussions in London, we decided to manage the entities based on a `Project`. We have ManyToOne between a User and Project, which means a User can be assigned to one Project, and multiple users can be in a single project.  If we want to allow above feature, we have to revise our Schema and relationships. Making it to ManyToMany would work. This will add some complexity in the validations of each query and work-flow. 
The only way-out for this would be create a new user as the PROJECT-ADMIN of P_2, according to current implementation. 
We should discuss the priority and the estimation to plan the implementation and milestones.

**Comment by blootsvoets** [comment]
Can multiple `SYS_ADMIN` be assigned? Would be useful to avoid password sharing. Similar for `PROJECT_ADMIN`.

**Comment by nivemaham** [comment]
Multiple `SYS_ADMIN` and `PROJECT_ADMIN` for a project are now allowed according to [issue16](https://github.com/RADAR-CNS/ManagementPortal/issues/16)

**Comment by blootsvoets** [comment]
This is done.
