### ISSUE TITLE
reduce horizontal space consumed by "External Link"

### ISSUE THREAD

**Issue by afolarin** [RADAR-base/ManagementPortal#172]
Would be perhaps better to reduce the horizontal space consumed in the management portal Project view, it is probably better to put the External Link URL as a hyperlink on the External ID? I don't think having the raw URL in the table adds much.

I think this would fit a little better on normal screens.

**Comment by nivemaham** [comment]
@afolarin We could do that indeed, given that we have an external link when we have an external-id. For redcap it is valid. Not sure whether it will hold if we try to refer other systems.

**Comment by dennyverbeeck** [comment]
Good idea indeed, we could add a button to the final column labeled 'External' or something like that. @afolarin How often would this link be used? If it's used only rarely, we can remove it from the table altogether. You would then need to first click the participant id to go to the details view and then visit the external link from there. But if this is only rarely used the benefit of a cleaner table probably outweighs the cost of the occasional extra click.
