### ISSUE TITLE
Investigate the best way to associate fitbit accounts

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/ManagementPortal#206]
There is a need to associate Fitbit accounts with subjects preferably on the MP so we don't have to create a manual map of this association data. Whats the best way @nivemaham @mbegalevibrent @dennyverbeeck @blootsvoets ?

**Comment by blootsvoets** [comment]
If you would go through an MP-only workflow, it would be:
1. Create a Fitbit passive source type in RADAR-Schemas specifications along with the schemas.
2. The Fitbit source  type will get detected in MP
3. Add the Fitbit source type to an MP project
4. Create a Fitbit source with the corresponding Fitbit API key as source ID.
5. Add the newly created source to a user.
6. The Fitbit source connector could periodically query the management portal on whether any users got a new Fitbit source mapping.

This workflow may be a bit verbose though. In a previous project, we had a basic interface served directly from the source connector to associate user IDs with API keys while also getting OAuth2 authorization. If that would be the workflow, you could do the following:
1. Create a Fitbit passive source type in RADAR-Schemas specifications along with the schemas.
2. The Fitbit source  type will get detected in MP
3. Add the Fitbit source type to an MP project WITH dynamic registration = true
4. The Fitbit connector registers new sources as they are registered through its own portal. The sourceId can be directly added, or added through the attribute map.
5. The Fitbit connector periodically checks if those sources are still registered.

Probably the second route would be more user-friendly.

**Comment by yatharthranjan** [comment]
@blootsvoets I also suggested the first approach to @mbegalevibrent . Can you please explain point 4 in the 2nd way you described above? Does it require to create the attribute map manually every time a new Fitbit is added to a subject? Is it okay to have source registration functionality in 2 separate places in the same system?

**Comment by blootsvoets** [comment]
Point 4 of the second approach entails creating a simple website with simple webservice with the connector, for example with an embedded jetty server in the source connector. That would register sources with the necessary attributes, just like the pRMT does. The manual part of this whole thing would be navigating the portal and entering the correct credentials or logging in a subject. Workflow 1 is also possible, but then you can do very few customizations for interacting with the Fitbit API.

**Comment by blootsvoets** [comment]
@mbegalevibrent @yatharthranjan @nivemaham Here is a possible flow to link Fitbit users and sources to the management portal:

Web app logs into management portal using with a project admin account:
```
POST /managementportal/oauth/token
Content-Type: application/x-www-form-urlencoded
grant_type=password&username=...&password=...&client_id=fitbitPortal&client_secret=...
{"accessToken": "abcdef", ...}
```
This will give a project admin access to all users in its projects.
First, select the projects where you are project admin:
```
GET /managementportal/api/users/{username}
Authorization: Bearer abcdef
{
  ...
  "roles": [{
    "authorityName": "PROJECT_ADMIN",
    "projectName": "radar",
    ...
  }]
}
```
Either present this as a list or as a dropdown.

To list all subjects in a project, then call
```
GET /managementportal/api/projects/{projectName}/subjects
Authorization: Bearer abcdef
[
  {
     "login": "joris",
     "attributes": {},
     "sources": {
        "sourceTypeId": 1,
        "sourceId": "abcd-efea",
        "sourceTypeProducer": "Fitbit",
        "sourceTypeModel": "Charge HR",
        "sourceTypeCatalogVersion": "1.0.0"
     }
     "project": {
        "sourceTypes": {
            "id": 1,
            "model": "Charge HR",
            "producer": "Fitbit",
            "sourceTypeCatalogVersion": "1.0.0",
            "canRegisterDynamically": true,
        }
     }
  }
]
```

To update the attributes of a subject, call
```
PUT /api/subjects
{
   "login": "joris",
   "attributes": {
       "fitbit.userId": "asbas",
       "fitbit.refreshToken": "adbada"
   }
}
```

Get it at any time with
```
GET /api/subjects/joris
{
   "login": "joris"
   ...
}
```

Once you retrieve the device Fitbit IDs, you can call
```
POST /api/subjects/joris/sources
{
   "sourceName": "abcded"
   "sourceTypeId": 1, OR "sourceTypeProducer": "Fitbit", "sourceTypeModel": "Charge HR", "sourceTypeCatalogVersion": "1.0.0"
   "attributes": {
      "fitbitUserSourceId": 1,
      "fitbitSourceId": "abcded"
   }
   ...
}
Response:
{
  "sourceId": "asdfa",
   "sourceName": "abcded-asdfa"
   "sourceTypeId": 1,
   "sourceTypeProducer": "Fitbit",
   "sourceTypeModel": "Charge HR",
   "sourceTypeCatalogVersion": "1.0.0"
   "attributes": {
      "fitbitUserSourceId": 1,
      "fitbitSourceId": "abcded"
   }
   ...
}
```

The `sourceId` property is the one that should be added in Kafka requests. 
Right now that only works once per source type, the second time a source of the same type is registered it will respond with HTTP status code 409 conflict.

In the source connector, you will not act on behalf of a user, so you should log in with OAuth `client_credentials` grant type instead.
```
POST /managementportal/oauth/token
Content-Type: application/x-www-form-urlencoded
grant_type=client_credentials&client_id=fitbitConnector&client_secret=...
{"accessToken": "abcdef", ...}
```

In the source connector, you can now use the following `ObservationKey` as a key for all records:
`{"projectId": {"string": "radar"}, "userId": "joris", "sourceId": "asdfa"}`.

In RADAR-Schemas, ensure that the Fitbit Charge HR is registered in `specifications/passive/fitbit_1.0.0.yml` with the corresponding schemas in `commons/passive/fitbit/`. In ManagementPortal, create two OAuth clients: `fitbitPortal` with `password` grant type and `fitbitConnector` with `client_credentials` grant type.

**Comment by yatharthranjan** [comment]
@mbegalevibrent please note that the schemas and specs are crucial for registration on ManagementPortal (It creates sourceTypes using these) and sending data into the platform. So this should be the first step.

**Comment by yatharthranjan** [comment]
@blootsvoets in the following call 
```
GET /managementportal/api/projects/{projectName}/subjects
Authorization: Bearer abcdef
[
  {
     "login": "joris",
     "attributes": {},
     "sources": {
        "sourceTypeId": 1,
        "sourceId": "abcd-efea",
        "sourceTypeProducer": "Fitbit",
        "sourceTypeModel": "Charge HR",
        "sourceTypeCatalogVersion": "1.0.0"
     }
     "project": {
        "sourceTypes": {
            "id": 1,
            "model": "Charge HR",
            "producer": "Fitbit",
            "sourceTypeCatalogVersion": "1.0.0",
            "canRegisterDynamically": true,
        }
     }
  }
]
```
The Charge HR source mentioned has not been registered yet so how is it in the response ? Doesn't it need to be first registered dynamically using - 

```
POST /api/subjects/joris/sources
{
   "sourceName": "abcded"
   "sourceTypeId": 1, OR "sourceTypeProducer": "Fitbit", "sourceTypeModel": "Charge HR", "sourceTypeCatalogVersion": "1.0.0"
   "attributes": {
      "fitbitUserSourceId": 1,
      "fitbitSourceId": "abcded"
   }
   ...
}
```

**Comment by blootsvoets** [comment]
It could have been registered in a previous call. This is just an example to see the response structure.

**Comment by nivemaham** [comment]
@yatharthranjan . You are right. The above lists just the APIs and responses to give some idea on what would be necessary. The request body would contain sources attached to the subject and indeed if the fitbit is not registered it wouldn't be in the response. But once the dynamic registration happens it will be listed.

**Comment by yatharthranjan** [comment]
Okay guys thanks for the clarification. I was just kind of following it as a step by step flow and got confused. This looks good to me.

**Comment by yatharthranjan** [comment]
Just a suggestion. There is also a Human Readable identifier for each subject. Would it be better to list the subjects using that if its present otherwise using the `login` if the Human Readable identifier is not present. This will make it easier for the recruiters to read and reduce any manual errors.

**Comment by nivemaham** [comment]
What do you mean by listing a subject by human-readable-identifier. We can include it as a property in the response. But it shouldn't change the API work-flow. Right?

**Comment by yatharthranjan** [comment]
Yes it will not change the API flow. Just for the fitbit connector portal when it lists the subjects for a project and the user has to select from that list. Just to reduce any chances of human error.

**Comment by nivemaham** [comment]
OK. It should be covered by fitbit portal then

**Comment by blootsvoets** [comment]
Indeed, this is the same approach pRMT takes: human-readable-identifier if present, login otherwise.

**Comment by yatharthranjan** [comment]
Done
