### ISSUE TITLE
ManagementPortal-client to use standard Java Date instead of Date from joda.

### ISSUE THREAD

**Issue by nivemaham** [RADAR-base/ManagementPortal#222]
Current distrubution of management-portal client generates objects with joda DateTime object. Instead it is better to use Data Time objects from java to ensure the compatibility with its clients

**Comment by blootsvoets** [comment]
Would that be the new date classes? [`java.time.Instant`](https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html), `ZonedDateTime` etc.

**Comment by nivemaham** [comment]
Yes. What we have in the DTOs used in MP are ZonedDateTime.

**Comment by yatharthranjan** [comment]
Is this still an issue, i see there is refactor of the client to kotlin so not sure.

**Comment by blootsvoets** [comment]
This is fixed 👍🏼
