### ISSUE TITLE
Update sources permissions

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-base/ManagementPortal#224]
Should the permission for updating the sources of a subject not be `SUBJECT_UPDATE` instead of `SUBJECT_READ`? See on the following line:

https://github.com/RADAR-base/ManagementPortal/blob/5ed53ba3c41a4243e5a1a64f23d6c0a578b39799/src/main/java/org/radarcns/management/web/rest/SubjectResource.java#L428

**Comment by yatharthranjan** [comment]
I think it is just getting the sources of the subject, not updating them according to the JAVA doc here - 

https://github.com/RADAR-base/ManagementPortal/blob/5ed53ba3c41a4243e5a1a64f23d6c0a578b39799/src/main/java/org/radarcns/management/web/rest/SubjectResource.java#L413

**Comment by blootsvoets** [comment]
yes, my bad! I looked at the `GetMapping` instead of the `PostMapping`
