### ISSUE TITLE
Link source in test setup

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-base/ManagementPortal#226]
Should the following line

https://github.com/RADAR-base/ManagementPortal/blob/5ed53ba3c41a4243e5a1a64f23d6c0a578b39799/src/main/resources/config/liquibase/subject_sources.csv#L2

be `"2";"1"` to map `"sub-1"` to a source? Also it seems that admin has no roles by default, is that intentional?

**Comment by nivemaham** [comment]
@blootsvoets No. It should be "1";"1" and currently `sub-1` has a source mapped in the test-data. Note here we have to use the `SUBJECTS_ID` which is the primary key of the `subjects` table, not the `USER_ID`. 
Admin has a role assigned. However, it is handled in different [file](https://github.com/RADAR-base/ManagementPortal/tree/master/src/main/resources/config/liquibase).
The reason for handling these separately is that we want to load different data-set in different profiles.

**Comment by nivemaham** [comment]
Closing this as it is already solved
