### ISSUE TITLE
Filter user management view

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/ManagementPortal#240]
Is there a way to sort or filter the users based on their role. This is needed when, suppose, someone wants to look at just the project admins and there are a lot of participants so its hard to search through all of them.

**Comment by nivemaham** [comment]
We can enable sorting by roles like other columns quickly if necessary. For filters, I prefer to investigate for a best solution whether native filter query or elasticsearch.

**Comment by yatharthranjan** [comment]
Okay cool. I think we can wait for the search functionality. i will change the label to feature

**Comment by afolarin** [comment]
related #236
