### ISSUE TITLE
As project analyst, a project shows up but is not accessible

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-base/ManagementPortal#254]
Right now, if I log in as a project analyst, I am not able to access my settings, password reset page, or even the project that I am assigned to.

As a project analyst, I would expect to be able to see all participants, sources and history for the project that I am assigned to. Also the password reset page and account page should be accessible.

**Comment by nivemaham** [comment]
PROJECT-ANALYST view is not implemented yet. Only the PROJECT_ADMIN and SYSTEM_ADMIN are the authorities supported from UI perspective. I will define the permissions and allow the UI and actions accordingly.

**Comment by Bdegraaf1234** [comment]
Project analyst role is not implemented
