### ISSUE TITLE
Fix API doc on GitHub pages

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-base/ManagementPortal#257]
The swagger API doc on GitHub pages now links to the old radar-cns.github.io, which should be radar-base.github.io. It is also out of date. It might be good to auto-generate these docs after a release using Travis.

**Comment by dennyverbeeck** [comment]
Fixed the script to auto-generate and push the docs in [this commit](https://github.com/RADAR-base/ManagementPortal/commit/4de256bac50b2c7f78324f4b3342966cf41260fd). Also fixed references from radar-cns to radar-base in gh-pages. Whenever we tag a release the apidoc and javadoc should be automatically updated again.
