### ISSUE TITLE
Auth API returns duplicate `access-control-allow-origin`

### ISSUE THREAD

**Issue by herkulano** [RADAR-base/ManagementPortal#258]
When the request has an `origin` set in the headers the API returns a duplicate `access-control-allow-origin`, which is not allowed by browsers.

![screen shot 2018-04-14 at 11 49 59](https://user-images.githubusercontent.com/125300/38767657-19fb047e-3fee-11e8-9082-6dffb913aaf6.png)

**Comment by nivemaham** [comment]
@blootsvoets can I close this issue? I assume it is resolved from radar-docker side.
