### ISSUE TITLE
Investigate more compact signature for JWTs

### ISSUE THREAD

**Issue by dennyverbeeck** [RADAR-base/ManagementPortal#259]
People have reported issues scanning the QR code. The RSA signature is quite big and blows up the amount of data encoded in the QR code, this might cause issues when it is displayed on lower resolution screens. One option is to switch to ECDSA as a signing algorithm wich produces more compact signatures. Things to check:
- Existing access tokens with RSA signature should still be accepted
- Existing refresh tokens with RSA signature should still be accepted
- Using an RSA signed refresh token should return new access and refresh tokens with the new signature

**Comment by blootsvoets** [comment]
Additional room for decreasing refresh token size: services need to know what sources and roles a user has, using the access token. For that purpose, that information is not necessary on the refresh token. Is it possible to differentiate between these two tokens in that way? So to remove all properties on the refresh token that are not strictly necessary?

**Comment by dennyverbeeck** [comment]
Since JWT is entirely stateless, the refresh token also encodes the information to generate a new access token. So unfortunately we can not remove this information from the refresh token. When a large amount of bytes needs to be encoded in a QR code, people tend to move to a 'meta' QR code ([source](https://softwareengineering.stackexchange.com/a/317410)). Basically we encode a URL in the QR code, and put the information at the URL. It would be pretty straightforward to implement this in MP. This would also allow us to deliver as much information as we want next to the refresh token, for instance the base URL as suggested in #262.
The downside is that this would require a change on the side of the apps. Instead of `Read QR code > Extract refresh token`, the flow would become `Read QR code > Perform GET request to URL > Extract refresh token`. However since we now only have a limited number of apps, it would be a better time to do it now then to do it later. What are your thoughts @blootsvoets @nivemaham ?

**Comment by dennyverbeeck** [comment]
Meta-QR codes could potentially also bypass the need for deeplinks #266. If we keep the URL short enough the URL can be typed in manually in the event of a scan failure. Still a bit of a pain, but the likelihood of scan failure should decrease drastically if we're just encoding a URL in the QR code.

**Comment by blootsvoets** [comment]
Possibly the deep links can stay, as an alternative to typing in the long URL. Since the URL by itself is not useful to anything except given client. For example, by making the link appear as the URL that you can type in, but actually link to the deep link of given client. That way, people can copy/paste the link into an email client and it should work on the participants phone.

**Comment by nivemaham** [comment]
Finally, I finished all these issues related to reducing the size of QR code. If we will have deep links and we already have ECDSA algorithm for compact QR codes, I'm wondering whether we really need the `metaQR` code in addition. If deep-links can share this refresh-token that only works once, it looks like a secure option too. I would say we first pass the ECDSA to production (at least not for milestone 0.4.0) and let the users test and implement the `metaQR` code on demand if the issue still persist.  What is your opinion @blootsvoets @dennyverbeeck

**Comment by dennyverbeeck** [comment]
Closed by #268
