### ISSUE TITLE
Investigate embedding base URL in QR code

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-base/ManagementPortal#262]
Investigate whether a second property should be added to the QR code, next to `refreshToken`, that contains the base URL for the RADAR-Docker installation. That way the app can be auto-configured to send data to the right server.

Potential pitfall: if a participant gets a printed-out QR code, a malicious party could change the URL, print out the modified QR code and coax users to send data to their own server. To my mind this is a scenario impossible to prevent with auto-configurable endpoints, since clients have no way to verify what the original server was and the configured endpoint can always lie to them.

@dennyverbeeck @nivemaham @yatharthranjan @afolarin what do you think

**Comment by nivemaham** [comment]
Closed by #295
