### ISSUE TITLE
Add authorization header in swagger

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/ManagementPortal#263]
Add authorization header in swagger so that it can be entered via the Swagger UI. Right now the `try it out` feature in the swagger UI is not useful as there is no authorization it always returns 401.

**Comment by nivemaham** [comment]
There is authentication in the swagger, but you have to be logged in to MP. It reads the current token from local-storage.

**Comment by yatharthranjan** [comment]
Okay thanks. Closing this now
