### ISSUE TITLE
OAuth2 code grant flow is broken

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-base/ManagementPortal#264]
The `/oauth/authorize` resource no longer provides a way to authorise a client application in order to get an access token and/or refresh token.  That means the OAuth 2.0 code grant flow is no longer functional. In effect, when I run

```
curl -v "http://localhost:8080/oauth/authorize?client_id=pRMT&response_type=code&redirect_uri=http://localhost/test&scope=READ.PARTICIPANT&state=12345" -u admin:admin
```
I expect to get an authorization code via the `redirect_uri`. Instead it redirects me to the login screen. If I omit the basic authentication `-u admin:admin`, I expect it  to show me a login screen, that will again redirect to the given URI providing my code with the state in the query string.

It does redirect me to `/login`, but when I then run (substituting the correct `_csrf` and `JSESSIONID`):
```
curl -d 'username=admin&password=admin&_csrf=5f97b32e-901d-4337-8f27-66a018793cbc' http://localhost:8080/login -H 'Cookie: JSESSIONID=MlpeV0H1e3vZv4v_b4coJIgqbVgaS7DGSUMeizxe' -H 'Content-Type: application/x-www-form-urlencoded' -v
```
It redirects me to the root page, instead of my provided `redirect_uri`. Also, I already provided a `state` variable which is a CSRF, so I would not expect to get another CSRF in the form.

**Comment by blootsvoets** [comment]
In any case, it would be good to document the flow.

**Comment by blootsvoets** [comment]
Okay, I think I've figured out the flow, and it partially works in the browser. The URL should be
```
http://localhost:8080/oauth/confirm_access?client_id=pRMT&client_secret=secret&response_type=code&redirect_uri=http://localhost/test
```
In that case the POST of the select variables points to the wrong URL: `/oauth/confirm_access/authorize` instead of `/oauth/authorize`. Creating a fix now.

**Comment by yatharthranjan** [comment]
Thanks. I also ran into this problem where it kept taking me to login screen
