### ISSUE TITLE
Allow generating deep links in addition to QR codes

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-base/ManagementPortal#266]
If QR code scanning fails, the management portal could generate a URL that also contains the necessary information. Each API client could define a prefix that the managementportal could create a link for to pass a refresh token to. Examples:

- The prefix `https://www.some.web.client.com/?refreshToken=` would pass the refresh token to `https://www.some.web.client.com/?refreshToken=abcdef`, which could parse the refresh token from the query string.
- The prefix `org.radarbase.prmt://oauth/refreshToken/` would map to `org.radarbase.prmt://oauth/refreshtoken/abcdef`, which could be handled by the pRMT app.

If the URL prefix is not defined for a client, the URL won't be generated. Alternatively, it can just show the plain text refresh token instead of the QR code. The prefix could be set in the oauth client csv file or in the oauth client web interface.

**Comment by yatharthranjan** [comment]
As an addition there can be a feature to email this directly from the MP.

**Comment by blootsvoets** [comment]
We’d have to be careful not to log the email address anywhere though, including the in-between webservers. In addition, sending the JWT over email creates an identifiable link between the subject and the RADAR participant in all intermediate webservers. I was thinking, could the MP use long one-time tokens instead of JWTs for the refresh tokens? That would solve some privacy issues and allows for much smaller QR codes.

**Comment by nivemaham** [comment]
I think now we can close this issue. @blootsvoets Am I right?

**Comment by blootsvoets** [comment]
I'd leave it open, to see if the new QR code resolves current issues with the camera. Or is the URL also printed to screen, in addition to showing the QR code?

**Comment by nivemaham** [comment]
No. It is not. I will leave it open.

**Comment by dennyverbeeck** [comment]
Fixed by #323
