### ISSUE TITLE
Add flag to discriminate test subjects

### ISSUE THREAD

**Issue by CallumSa** [RADAR-base/ManagementPortal#276]
It seems common to have test subjects in a RADAR project (not an actual enrolled participant). So far as I can see, there is no way to differentiate them apart from by externalId or by who they were created by (usually redcap for real and admin for test). The former is reliant on knowing what the externalId should be and hoping that no one makes a test account in a similar style. The latter may not always be true, if a true participant is enrolled outside of redcap somehow.

It would be nice if there were some field or subject type that can be set to explicitly show that a subject is for testing.

**Comment by nivemaham** [comment]
Hi Callum, I agree with your comments that it is not easy to distinguish test subjects and actual subjects. However, it is not a common practice to have an attribute to define whether it is a test subject or not. We encourage to create the test subjects as much as possible on the test environment.

**Comment by yatharthranjan** [comment]
Yes i agree. Also i am in the process of clearing out the test subjects and projects from production MP. BTW @CallumSa  is this causing problems on the data analysis side ?

**Comment by CallumSa** [comment]
Yeah, not having test subjects in real projects is probably the best solution. (There are still 5 currently, I'll send you their IDs Yatharth)

**Comment by yatharthranjan** [comment]
Yes callum, I deleted most of them. Please let me know if there are more. Closing this for now
