### ISSUE TITLE
Admin password should be configurable via Environment variable

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/ManagementPortal#289]
The admin password should be configurable via an environment variable by default unless changed via the portal. Related to https://github.com/RADAR-base/RADAR-Docker/issues/137

**Comment by nivemaham** [comment]
Why not just change the password from MP front-end?

**Comment by yatharthranjan** [comment]
This is for securing the MP before that happens. If the change is done on the front end then this env var will have no effect. This also helps keeps all the configuration consistent in one place when installing the stack.
If this is not trivial to do in the MP, then yes we can leave it as it not a requirement but something good to have.

**Comment by yatharthranjan** [comment]
Also there are more chance of someone not updating the password on the front end. But if it has to be configured as part of installation of the stack then there is definitely going to be better secured.
