### ISSUE TITLE
Fix Grant_type null issue

### ISSUE THREAD

**Issue by nivemaham** [RADAR-base/ManagementPortal#300]
Related version 0.4.0

When grant_type is not properly generated for during pair request and latest implementation ignores grant_type in access_token if not explicitly included.

**Comment by blootsvoets** [comment]
Because there are now probably tokens distributed without a grant type, I think the check should just be removed from TokenValidator. In any case, the grant type is only used as a check for client_credentials, which wouldn't use a refresh token.
