### ISSUE TITLE
Meta QR code expiry

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/ManagementPortal#346]
The low time period for the expiry of the meta token (1hr by default) means a lot of remote recruitments having problems.

It would be good if the MP displayed the expiry/timeout of the Token URL on the pair app dialog so the clinicians can make informed decisions.

Would also be good to have this configurable by admins on the MP (don't know if its already there but couldn't find any docs)

**Comment by nivemaham** [comment]
The meta-token timeout is [configurable](https://github.com/RADAR-base/ManagementPortal/blob/dev/src/main/resources/config/application-dev.yml#L114). You can use docker environment variables to configure it. We do recommend not to configure very large span as timeout for security reasons and meta-token can be easily refreshed with one click on the pair-app dialog.

**Comment by afolarin** [comment]
@nivemaham  good to know it is configurable and I agree the timing is sensitive here, was there any guidelines on the selection of 1 hr  (just for reference).

I think a lot of the time giving the MP user the knowledge that there is a short limit on the scan time window will help.

**Comment by nivemaham** [comment]
@afolarin I agree that the user should be informed about the timeout. We have already improved the activation email contents with timeout information. We will integrate some additional timeout information about meta-token in the dialog. However, It would be a one-time notification, which is displayed when the Meta-token is created.

**Comment by nivemaham** [comment]
And the selection of 1hour was not based on any guidelines or references.

**Comment by afolarin** [comment]
> We will integrate some additional timeout information about meta-token in the dialog. However, It would be a one-time notification, which is displayed when the Meta-token is created.
Perfect! It is more a prompt for the user issuing the QRcode/token (in case they were not aware of the 1hr limit).
