### ISSUE TITLE
Improve startup time

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-base/ManagementPortal#433]
Based on a profiling session, Spring component and classpath scanning is taking up the majority of the startup time of ManagementPortal. This could be reduced by using a fixed set of components, defined in XML, during startup. For reference:
https://stackoverflow.com/questions/5947713/spring-startup-performance-issues

**Comment by blootsvoets** [comment]
For Spring 5 only: https://stackoverflow.com/questions/47254907/how-can-i-create-a-spring-5-component-index/48407939#48407939

**Comment by blootsvoets** [comment]
Possible alternative: limit the amount of packages scanned in the annotation: https://github.com/RADAR-base/ManagementPortal/blob/9d5dc9d0cfd76205af516d4a15e6724015afe4ea/src/main/java/org/radarcns/management/ManagementPortalApp.java#L24

**Comment by yatharthranjan** [comment]
Just a heads up that component indexer currently does not work with springfox swagger. Issue - https://github.com/springfox/springfox/issues/2451

**Comment by blootsvoets** [comment]
Thanks for the notification about that. The issue also shows a workaround: https://github.com/springfox/springfox/issues/2451#issuecomment-437078201, we could try if that works?
