### ISSUE TITLE
Project API /api/projects data duplication and performance

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-base/ManagementPortal#443]
In the project DTO, there is a `sourceTypes` property, which has a `sourceData` property, which has again a `sourceType` property which duplicates information in the parent object. Could the child `sourceType` property be removed from `sourceData`, since it only duplicates data?

Also, would it be possible to remove the `sourceTypes` completely when querying for all projects, but rather reserve that for when a single project is being queried? Even in a single project, I'd think that `sourceData` is probably not necessary, only if `/api/projects/{projectId}/sourceTypes` is being queried.

**Comment by nivemaham** [comment]
Yes. I noticed that issue as well. I was thinking we could just add the source-type identifier in project and leave the rest. But your solution works as well. I will also check what would be best for the MP front-end rendering and make the changes.

**Comment by blootsvoets** [comment]
Source-type identifier would also be fine. The per-project source-data implementation will probably not be used in the current form in any case.
