### ISSUE TITLE
Cannot start web service with current webpack

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-base/ManagementPortal#446]
When running
```
yarn install
yarn start
```
I get the following errors:
```shell
# install
warning " > webpack-cli@3.3.2" has incorrect peer dependency "webpack@4.x.x".
warning " > webpack-dev-server@3.1.11" has incorrect peer dependency "webpack@^4.0.0".
warning "webpack-dev-server > webpack-dev-middleware@3.4.0" has incorrect peer dependency "webpack@^4.0.0".
...
# start
Error: Cannot find module 'webpack-cli/bin/config-yargs'
```
According to a short search, this is due to incompatibilities between the webpack-cli and webpack. An update to `package.json` would be needed.

**Comment by nivemaham** [comment]
Sorry. My bad. I was relying on the e2e test for this change. I ran it on my localhost for other changes. Missed this. Upgrading to web-pack 4 is not that straight forward. I had a look. But didn't succeed upgrading quickly. I will have a look at this.
