### ISSUE TITLE
OAuth client dialog does not save password

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-base/ManagementPortal#492]
A password was set in ManagementPortal OAuth dialog, and a popup indicated that the result was saved. Updating the config CSV file did work. As a check:

- [ ] No ManagementPortal restart was performed between saving the dialog and verifying the password.
- [ ] The client had the same password set for the duration of the test, e.g. there is no discrepancy between the Firebase settings and the defaults file.

**Comment by yatharthranjan** [comment]
Just a note. That on the ManagementPortal OAuth dialog the client secret field always displays empty even when a password is set. This could also be a source of confusion.

**Comment by mpgxvii** [comment]
I also experienced this a few times. It saves it and it works at first, it then gets reset a few days later. I experienced this when I modified the RADAR-Dashboard password.

**Comment by nivemaham** [comment]
During MP restarts, the content in the oauth-clients.csv is overriden on the database. As a fix, either modify the CSV or remove related client from the CSV.
