### ISSUE TITLE
After login on unauthorised screen, user is not redirected back

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-base/ManagementPortal#514]
It stays on the unauthorised page but it should redirect you back to the previously authorised page.

**Comment by nivemaham** [comment]
At the moment I have issued a simple fix to navigate back to home page. Redirecting to previous state results in few issues, especially redirecting back to urls that have popup, does not work with redirect automatically. I couldn't find the reason or solution for this issue. Plus currently, there are some inconsistent behavior on storing and navigating back to old state. I spent almost three days to find a solution that would work through out the app. But with no luck, I have decided to conclude the issue just by navigating to home page. this will at least avoid the user seeing the error-page when logged in.
