### ISSUE TITLE
Unable to authenticate new user 

### ISSUE THREAD

**Issue by sallymoon10** [RADAR-base/ManagementPortal#538]
After installing RADAR-BASE on my server, I logged in as admin and I followed the instructions here (https://radar-base.org/index.php/getting-started-with-radar-base/demo-using-prmt-app/) to create a new study and a new subject on the management portal and installed the PRMT app from the play store. However when I try to scan the QR code generated when I press pair app on the participant, it gives me an error saying authentication failed. 

Here are some screenshots of what the subject created looks like along with the settings for the prmt app under source types in case it helps. 

I followed instructions on a simliar github issue: https://github.com/RADAR-base/ManagementPortal/issues/486
and did the following:

1) enabled Dynamic Registration on ANDROID PHONE 1.0.0, ANDROID PHONE v1, OPENSMILE AUDIO 1.0.0, OPENWEATHERMAP API 0.1.0, RATE-AF PPG 0.1.0, RADAR pRMT 1.0.0,  RADAR pRMT v1 and RADAR pRMT 1.1.0 under source types
2) assigned all the above sources to the project

When I run bin/radar-docker logs managementportal-app, no errors seem to be appearing. 

Also when I view etc/managementportal/config/oauth_client_details.csv, the client_secret column remains empty. 

My domain is: mhiatsl.com

Any help would be greatly appreciated, thank you so much!! 

<img width="1152" alt="Screen Shot 2020-11-27 at 12 53 32 PM" src="https://user-images.githubusercontent.com/14798003/100483422-294c9d00-30b6-11eb-933c-2f1ed2ece2eb.png">
<img width="402" alt="Screen Shot 2020-11-27 at 1 36 06 PM" src="https://user-images.githubusercontent.com/14798003/100483438-37022280-30b6-11eb-99b1-ec6916038b8d.png">

<img width="1394" alt="Screen Shot 2020-11-27 at 1 41 32 PM" src="https://user-images.githubusercontent.com/14798003/100483456-47b29880-30b6-11eb-958e-2a764bf32e9b.png">
<img width="1394" alt="Screen Shot 2020-11-27 at 1 41 28 PM" src="https://user-images.githubusercontent.com/14798003/100483458-48e3c580-30b6-11eb-96db-0eda15efdfa1.png">

**Comment by Bdegraaf1234** [comment]
closing, please recreate if still an issue
