### ISSUE TITLE
Login successful BUT nothing is here

### ISSUE THREAD

**Issue by kafe09** [RADAR-base/ManagementPortal#552]
Hello,
we were able to successfully build RADAR-base on our server.
The login to the management-portal with our credentials (which are correct) does not show up an error.
**BUT nothing happens** - there is still the same surface (Are you a registered user? Sign in) as before a successful login.

What can we do, is there anything else we have to integrate? E.g. the RADAR dashboard?

Looking forward hearing from you soon! Thank you

BR
Kafe

**Comment by JustSamzy** [comment]
Hello,

We are also having this issue. Did you find a solution?

**Comment by Bdegraaf1234** [comment]
Closing, please recreate if still relevant
