### ISSUE TITLE
The Source Type box is not populated with the selected dropdown value

### ISSUE THREAD

**Issue by baixiac** [RADAR-base/ManagementPortal#587]
Administrator -> Projects -> Create new project -> Select source type. Then `[object Object]` will be displayed rather than the true selected value:

![source_type](https://user-images.githubusercontent.com/82581439/115267486-23bd2580-a131-11eb-971d-4e053383e628.png)

**Comment by yatharthranjan** [comment]
Yes 0nly happens during creation though. If you edit it later on it works fine

**Comment by blootsvoets** [comment]
@aykl could this be related to the new source type dialog?

**Comment by aykl** [comment]
@blootsvoets no, this is an older issue that I overlooked.

**Comment by blootsvoets** [comment]
Thanks @aykl for the quick fix!

**Comment by baixiac** [comment]
Nice work! 👍
