### ISSUE TITLE
redirect traffic from / to /managementportal/

### ISSUE THREAD

**Issue by Bdegraaf1234** [RADAR-base/ManagementPortal#724]
Right now all endpoints in prod builds (including docker images) are set to ```/managementportal/...```, while dev/local builds are expected at root (```/api/sitesettings``` vs ```/managementportal/api/sitesettings```)

Needing to alter requests between dev and prod builds should not be needed. We can fix this by rerouting traffic from root to /managementportal/.

this should likely be done in the ```proxy.conf.json``` file

**Comment by blootsvoets** [comment]
@Bdegraaf1234 this is fixed via #725, right?

**Comment by Bdegraaf1234** [comment]
We may have preemptively closed this one:

the current state requires the ALDS (`yarn start`) to actually point the logins to the right paths. If you just run `./gradlew bootRun -Pdev` you get connection refused because login requests are sent to `managementportal/oauth/*` instead of `oauth/*`.
