### ISSUE TITLE
Limit CI workflow until PR is ready for review

### ISSUE THREAD

**Issue by Bdegraaf1234** [RADAR-base/ManagementPortal#737]
Right now a lot of tests are being run on every commit, while the majority of problems arises from the e2e tests. Stylefixes can and perhaps should be fixed when the pull request is ready for review to prevent the dev-cycle from being to long when fixing (remotely) failing e2e tests.

**Comment by blootsvoets** [comment]
The tasks can also be reordered or made (in)dependent of one another. The total test time will go up, but the result will be more parallel.

**Comment by blootsvoets** [comment]
Something else that might save you time in the long run is to add a git pre-commit or pre-push hook where you do the style checks. Then at least that part of the test is going to succeed remotely.
